Main/urls.py
from django.contrib import admin
from django.conf.urls import url

from django.urls import path,include
from django.contrib.auth import views as auth_views
from account.views import LoginView, RegisterView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls',namespace='account')),
    path('', include('ticket.urls',namespace='ticket')),
    path('', include('django.contrib.auth.urls')),  
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register')  
]

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views

from . import views
app_name = 'ticket'
urlpatterns = [                   
    path('dashboard',view=views.dashboard, name='dashboard'),
    path('calculate',view=views.calculate, name='calculate'),
    path('clustering',view=views.clustering, name='clustering'),
    path('identify',view=views.identify, name='identify'),
    path('view_existing_samples',view=views.view_existing_samples, name='view_existing_samples'),
    path('edit/<str:id>',view=views.edit, name='edit'),
    # ajax
    path('upload_csv',view=views.upload_csv, name='upload_csv'),   
    path('process_csv',view=views.process_csv, name='process_csv'), 
   
]

content/templates/authroot.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="icon" type="image/png" href="{% static 'images/fav.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/intlTelInput.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>    
    <script type="text/javascript" src="{% static 'js/intlTelInput.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sweetalert2.js' %}"></script>
</head>

<body>
    <div class="login-bg">
        <div class="login-bg-inner">
            <div class="row h-100 align-items-center">               
                <div class="col-lg-12">
                  {% block content %}
                  {% endblock %}
                </div>
            </div>
        </div>
    </div>
   <div class="process-comm" id="loading">
      <div class="spinner">
         <div class="bounce1"></div>
         <div class="bounce2"></div>
         <div class="bounce3"></div>
      </div>
   </div>
    <!-- core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
   
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

</body>

</html>

content/templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-touch">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	<title>TSL</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="keywords" content="">	
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
		
	<link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}">	
	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">	
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.canvasjs.min.js' %}"></script>
</head>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg static-top">
		<div class="container-fluid">
		  <a class="navbar-brand" href="/">TSR LOGO</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item active">
				<a class="nav-link" href="#">Help				  
				</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link btn_getting_started" href="#">Getting Started</a>
			  </li>			  
			</ul>
		  </div>
		</div>
	</nav>
	<div class="left_menu">
		<div class="left_side">
			<ul class="menu">
				<li class="{% if nav == 'sample' %} selected_menu_item {% endif %}">
					<a href="{% url 'ticket:dashboard' %}">
						<i class="fas fa-bookmark mr-2"></i>
						<span>Sample Generation</span> 
					</a>								
				</li>
				<li class="{% if nav == 'calculate' %} selected_menu_item {% endif %}">
					<a href="{% url 'ticket:calculate' %}">
						<i class="fas fa-bookmark mr-2"></i>
						<span>Calculate TSR 3D Keys</span> 
					</a>
				</li>
				<li class="{% if nav == 'clustering' %} selected_menu_item {% endif %}">
					<a href="{% url 'ticket:clustering' %}">
						<i class="fas fa-bookmark mr-2"></i>
						<span>Clustering</span> 
					</a>								
				</li>
				<li class="{% if nav == 'identify' %} selected_menu_item {% endif %}">
					<a href="{% url 'ticket:identify' %}">
						<i class="fas fa-bookmark mr-2"></i>
						<span>Identify Common Keys</span> 
					</a>								
				</li>
			</ul>
			<hr>
			<ul class="menu">
				<li class="{% if nav == 'view' %} selected_menu_item {% endif %}">
					<a href="{% url 'ticket:view_existing_samples' %}">
						<i class="fas fa-bookmark mr-2"></i>
						<span>View Existing Samples</span> 
					</a>								
				</li>							
			</ul>
		</div>
	</div>
	<main>
		<div class="container-fluid">
			<div class="row">				
				<div class="col-lg-12">
					{% block content %}
					
					{% endblock %}
				</div>
			</div>
		</div>		
	</main>
	<footer>
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12 text-center">
					<ul class="footer_link">
						<li>
							<a href="">Team</a>
						</li>
						<li>
							<a href="">Publications</a>
						</li>
						<li>
							<a href="">Citing Us</a>
						</li>
						<li>
							<a href="">TSR LOGO</a>
						</li>
						<li>
							<a href="">About</a>
						</li>
						<li>
							<a href="">Useful Links</a>
						</li>
						<li>
							<a href="">Support</a>
						</li>
					</ul>
					<hr style="border-top: 2px solid rgba(0,0,0,.8);">
					<span>
						&copy;TSR Team Privacy - Terms
					</span>
				</div>
			</div>
		</div>
	</footer>
	<div id="loading">
		<div class="lds-ring" ><div></div><div></div><div></div><div></div></div>
	</div>
	
	<!--theme-layout end-->
	 <form action="" method="post">
		{% csrf_token %}
	 </form>
	
	<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>	
	<script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/sweetalert2.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>


</body>

</html>